services:
  create-astral:
    environment:
      EULA: "FALSE"
    ports:
      - 25565:25565
    volumes:
      - ./ops.json:/data/ops.json
      - astral-world:/data/world
      - astral-config:/data/config
      - astral-mods:/data/mods
      - ./extra_mods:/extra_mods
      - ./extra_datapacks:/extra_datapacks
volumes:
  astral-world:
  astral-config:
  astral-mods: