services:
  create-astral:
    build: .
    environment:
      EULA: "FALSE"
      ALLOCATED_RAM: ${ALLOCATED_RAM}
      RCON_PASSWORD: ${RCON_PASSWORD}
    ports:
      - 25565:25565
    volumes:
      - ./ops.json:/data/ops.json
      - astral-world:/data/world
      - astral-config:/data/config
      - astral-mods:/data/mods
      - ./extra_mods:/extra_mods
      - ./extra_datapacks:/extra_datapacks
      - ./rcon.yaml:/etc/rcon.yaml
volumes:
  astral-world:
  astral-config:
  astral-mods: